### ISSUE TITLE
Create Firebase account to CV and migrate local data

### ISSUE THREAD

**Issue by raulfdm** [raulfdm/cv#5]
## TODO
- [ ] Migrate local data to realtime database
- [ ] get data should be public
- [ ] set data should be private (key/token required)

**Comment by raulfdm** [comment]
#35
